
#General configuration settings
[general]
	scaledFallDamage = false
	scaledMotion = false
	scaledReach = false
	scaledAttack = false
	scaledDefense = false
	scaledHealth = false
	scaledItemDrops = false
	scaledProjectiles = false
	scaledExplosions = false
	keepAllScalesOnRespawn = false
	accurateNetherPortals = false
	scalesKeptOnRespawn = []
	enableCommands = false
	enableDebugCommands = false

