name = "Serendipity Modpack"
author = "Javinyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c3892501fbc4910db3e99214695b16503ddccf331ffa8914cf5ee315dbec580"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "configureddefaults/config/paxi/datapacks"
