name = "Serendipity Modpack"
author = "Javinyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2589aa98b35a7d512d1bafabc70b11e447a5d62aa30fe9f27f19a2c94414450d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"

[options]
datapack-folder = "datapacks"
