name = "SerendipiCraft"
author = "Serendipity"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fad3916009d1fe4d455f8005b6662b28c28057c41b9afcf09a89a8d889b69d7c"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
