name = "Serendipity Modpack"
author = "Javinyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c65b2b4bc7408313a0f2b412ed01dce3d41a34f46da8d030f414630be37ba87a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "configureddefaults/config/paxi/datapacks"
