name = "Serendipity Modpack"
author = "Javinyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04a4bb6dd95d717bac7018d5a2c930e7b1383e6a1da17a5c896fb8fd6c354876"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "configureddefaults/config/paxi/datapacks"
