name = "Serendipity Modpack"
author = "Javinyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43b65a0bb567c4901cfbbf0aae6fba58aa857016c7b5da5a4b3620012574ddcf"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"

[options]
datapack-folder = "datapacks"
