
#Client only settings, mostly things related to rendering
[client]
	#Enable NeoForge to queue all chunk updates to the Chunk Update thread.
	#May increase FPS significantly, but may also cause weird rendering lag.
	#Not recommended for computers without a significant number of cores available.
	alwaysSetupTerrainOffThread = false
	#EXPERIMENTAL: Enable the NeoForge block rendering pipeline - fixes the lighting of custom models.
	experimentalForgeLightPipelineEnabled = false
	#When enabled, NeoForge will show any warnings that occurred during loading.
	showLoadWarnings = true
	#Set to true to use a combined DEPTH_STENCIL attachment instead of two separate ones.
	useCombinedDepthStencilAttachment = false
	#[Deprecated for Removal] IPv6 addresses will always be compressed
	compressLanIPv6Addresses = true
	#During block model baking, manually calculates the normal for all faces.
	calculateAllNormals = false
	#When enabled, a slightly biased Direction#getNearest calculation will be used to prevent normal fighting on 45 degree angle faces.
	stabilizeDirectionGetNearest = true

