version = 1
itemFrameLODRange = 16
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 3
includeMangroveRoots = true
entityModelCulling = true
endGatewayCulling = true
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = false
itemFrameMapCulling = true
useItemFrameLOD = true
useItemFrame3FaceCulling = true
powderSnowCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
minecraft = true